import { FieldConfig } from "../../types/FieldConfig";

export interface Client {
  id?: string; // UUID or database ID
  client_id: string; // Custom client identifier like "C001"
  name: string;
  contact_person: string;
  email: string;
  phone: string;
  address: string;
  city: string;
  state: string;
  country: string;
  postal_code: string;
  gst_number?: string; // Optional for tax identification
  pan_number?: string; // Optional for India-specific use
}



export const clientFields: FieldConfig[] = [
  // { name: "client_id", label: "Client ID", type: "text", required: true }, // usually autogenerated
  { name: "name", label: "Client Name", type: "text", required: true },
  { name: "contact_person", label: "Contact Person", type: "text", required: true },
  { name: "email", label: "Email", type: "email", required: true },
  { name: "phone", label: "Phone", type: "text", required: true },
  { name: "address", label: "Address", type: "text", required: true },
  { name: "city", label: "City", type: "text", required: true },
  { name: "state", label: "State", type: "text", required: true },
  { name: "country", label: "Country", type: "text", required: true },
  { name: "postal_code", label: "Postal Code", type: "text", required: true },
  { name: "gst_number", label: "GST Number", type: "text", required: false },
  { name: "pan_number", label: "PAN Number", type: "text", required: false },
];

export const clientTableColumns = [
  { name: "name", label: "Client Name" },
  { name: "contact_person", label: "Contact Person" },
  { name: "email", label: "Email" },
  { name: "phone", label: "Phone" },
  { name: "address", label: "Address" },
  { name: "city", label: "City" },
  { name: "state", label: "State" },
  { name: "country", label: "Country" },
  { name: "postal_code", label: "Postal Code" },
];

